{% set name = "elastic-transport" %}
{% set version = "8.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e755f38f99fa6ec5456e236b8e58f0eb18873ac8fe710f74b91a16dd562de2a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - urllib3 >=1.26.2,<3
    - certifi

test:
  imports:
    - elastic_transport
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/elastic/elastic-transport-python
  summary: Transport classes and utilities shared among Python Elastic client libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ezimuel
    - joshmock
    - pquentin
    - miguelgrinberg
