{% set name = "elastic-transport" %}
{% set version = "8.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9cac4ab5cf9402668cf305ae0b7d93ddc0c7b61461d6d1027850db6da9cc5742

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python >=3.8
  run:
    - python >=3.8
    - urllib3 >=1.26.2,<3
    - certifi

test:
  imports:
    - elastic_transport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/elastic-transport-python
  summary: Transport classes and utilities shared among Python Elastic client libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ezimuel
    - joshmock
    - pquentin
    - miguelgrinberg
