{% set name = "elastic-transport" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elastic-transport-{{ version }}.tar.gz
  sha256: 8e07b52fd71e3f209ec2053c2b3953b22dcd085143669cfe6e28bb4ed4af94c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - urllib3 >=1.26.2,<2

test:
  imports:
    - elastic_transport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/elastic-transport-python
  summary: Transport classes and utilities shared among Python Elastic client libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sethmlarson
