{% set name = "elastic-transport" %}
{% set version = "8.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elastic-transport-{{ version }}.tar.gz
  sha256: b9ad708ceb7fcdbc6b30a96f886609a109f042c0b9d9f2e44403b3133ba7ff10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - urllib3 >=1.26.2,<2

test:
  imports:
    - elastic_transport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elastic/elastic-transport-python
  summary: Transport classes and utilities shared among Python Elastic client libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ezimuel
    - joshmock
    - pquentin
